### ISSUE TITLE
Custom OAuth why?

### ISSUE THREAD

**Issue by jbonnett92** [Shoogn/OAuth20Server#1]
Hi,
Microsoft has a package for identity that covers OpenId / OAuth, I see that you used the tokens one, I'd just like to know the reasoning behind this?

Thanks

**Comment by NeutraleNull** [comment]
They do not create an authorization server, it is only consuming API. You are required to use third party software like the deprecated IdentityServer4 to get the same.

**Comment by jbonnett92** [comment]
No you're not, check this out: [https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow)

**Comment by NeutraleNull** [comment]
Yes this is using azure AD. It is not a lib you can use in your server and
have full control over it.

Am Di., 28. Feb. 2023 um 20:15 Uhr schrieb Jamie Bonnett <
***@***.***>:

**Comment by Shoogn** [comment]
Hi @jbonnett92 
As @NeutraleNull said to you the OpenId / OAuth2 are consuming APIs, so you have to build your Authorization Server, or you can use a free or paid one to integrate it with your apps.
