### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by computeridea** [Shoogn/OAuth20Server#4]
hi, great job,  at least did you implemented the token response?  i see the code and lass, but i didn't see the response anywhere, can yu help me to understand?

i added the following code in the login, but i don't want to duplicate code 

`if (loginResult.Succeeded)
            {
                var tokenHandler = new JwtSecurityTokenHandler();
                var key = Encoding.ASCII.GetBytes("ChiaveChiaveChiaveChiaveChiaveChiave");
                var tokenDescriptor = new SecurityTokenDescriptor
                {
                    Subject = new ClaimsIdentity(new Claim[]
                    {
                        new Claim(ClaimTypes.Name, user.Id)
                    }),
                    Expires = DateTime.UtcNow.AddDays(7),
                    SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(key), SecurityAlgorithms.HmacSha256Signature)
                };
                var token = tokenHandler.CreateToken(tokenDescriptor);
                var tokenString = tokenHandler.WriteToken(token);

                return new LoginResponse { Succeeded = true,Token= tokenString };
            }`

can you help me,  to call it by postMan, 
where is the endpoint to call and how  i should write the request parameters??

**Comment by Shoogn** [comment]
Hi, there no implementation to generate the token directly (by using credential)  , the current available option is by openId connect.
