### ISSUE TITLE
Typo in appsettings.json for server

### ISSUE THREAD

**Issue by bartlomiejpopko** [Shoogn/OAuth20Server#9]
There is a typo in files appsettings.json and appsettings.Development.json. Should be "OAuthOptions" Instead of "OAuthOption".

**Comment by Shoogn** [comment]
Very happy you find this typo, today I searched more than one hour to figure out why the issuer is coming null when writing token by JwtTokenHandler, but lastly I find this out, and update it with new feature added, UserInfo endpoint

**Comment by Shoogn** [comment]
Now solved!
